### ISSUE TITLE
mantic: broken automatic partition setup

### ISSUE THREAD

**Issue by jbicha** [canonical/ubuntu-desktop-installer#2252] opened 2023-07-18 17:59 UTC
- Ubuntu Desktop 23.10 "mantic" 2023-07-18

Test Case
-------------
I am using Ubuntu 23.10 as my host. In GNOME Boxes, I created a 23.10 guest using today's ISO.

I clicked all the default options until I get to this confirmation screen with missing details in the devices and partitions sections.

![Screenshot from 2023-07-18 13-52-36](https://github.com/canonical/ubuntu-desktop-installer/assets/876259/5966cb5d-5960-4d50-94c0-f37802a9e489)

Afterwards, I clicked Install and finished the rest of the dialog but it looked like the installer couldn't actually install anything so I was just left at the slideshow stage. No other errors or glitches were shown.

**Comment by jpnurmi** [comment] 2023-07-18 18:10
Hey @jbicha, do you still have access to the system? Any chance to get the logs from `/var/log/installer`?

**Comment by jpnurmi** [comment] 2023-07-18 18:46
Never mind, I'm just too used to bumping up the VM specs! :man_facepalming: I was able to reproduce the issue with the default 25.0 GiB storage.

**Comment by jpnurmi** [comment] 2023-07-18 18:52
We need to add handling for the `TOO_SMALL` reason introduced in canonical/subiquity#1694.
```
2023-07-18 18:48:14.733330 DEBUG subiquity_client: GET http://localhost/storage/v2/guided?wait=true
2023-07-18 18:48:14.734688 DEBUG subiquity_client: ==> getGuidedStorageV2(true) {"status": "DONE", "error_report": null, "configured": null, "targets": [{"disk_id": "disk-vda", "allowed": [], "disallowed": [{"capability": "DIRECT", "reason": "TOO_SMALL", "message": null}, {"capability": "LVM", "reason": "TOO_SMALL", "message": null}, {"capability": "LVM_LUKS", "reason": "TOO_SMALL", "message": null}], "$type": "GuidedStorageTargetReformat"}, {"allowed": ["MANUAL"], "disallowed": [], "$type": "GuidedStorageTargetManual"}]}
```

**Comment by jpnurmi** [comment] 2023-07-19 07:19
With the default 25 GiB disk gnome-boxes offers for Ubuntu 23.10, Subiquity refuses guided reformat (`TOO_SMALL`) even though manual installation with the simplest possible partition layout installs fine.

- `GET /storage/v2/orig_config`
  ```json
  {"status": "DONE", "error_report": null, "disks": [{"id": "disk-vda", "label": "/dev/vda", "type": "local disk", "size": 26843545600, "usage_labels": [], "partitions": [{"offset": 1048576, "size": 26841448448, "usable": "YES", "$type": "Gap"}], "ok_for_guided": true, "ptable": null, "preserve": true, "path": "/dev/vda", "boot_device": false, "can_be_boot_device": true, "model": null, "vendor": null}], "need_root": true, "need_boot": true, "install_minimum_size": 17297309696}
  ```

- `GET a/storage/v2/guided`
  ```json
  {"status": "DONE", "error_report": null, "configured": null, "targets": [{"disk_id": "disk-vda", "allowed": [], "disallowed": [{"capability": "DIRECT", "reason": "TOO_SMALL", "message": null}, {"capability": "LVM", "reason": "TOO_SMALL", "message": null}, {"capability": "LVM_LUKS", "reason": "TOO_SMALL", "message": null}], "$type": "GuidedStorageTargetReformat"}, {"allowed": ["MANUAL"], "disallowed": [], "$type": "GuidedStorageTargetManual"}]}
  ```

- `POST a/storage/v2/add_partition {"disk_id": "disk-vda", "size": "26841448448", "wipe": "superblock", "mount": "/", "format": "ext4"}`
  ```json
  {"status": "DONE", "error_report": null, "disks": [{"id": "disk-vda", "label": "/dev/vda", "type": "local disk", "size": 26843545600, "usage_labels": [], "partitions": [{"size": 1127219200, "number": 2, "preserve": false, "wipe": "superblock", "annotations": ["new", "primary ESP", "to be formatted as fat32", "mounted at /boot/efi"], "mount": "/boot/efi", "format": "fat32", "grub_device": true, "boot": true, "os": null, "offset": 1048576, "estimated_min_size": -1, "resize": null, "path": "/dev/vda2", "$type": "Partition"}, {"size": 25714229248, "number": 1, "preserve": false, "wipe": "superblock", "annotations": ["new", "to be formatted as ext4", "mounted at /"], "mount": "/", "format": "ext4", "grub_device": null, "boot": false, "os": null, "offset": 1128267776, "estimated_min_size": -1, "resize": null, "path": "/dev/vda1", "$type": "Partition"}], "ok_for_guided": true, "ptable": "gpt", "preserve": false, "path": "/dev/vda", "boot_device": true, "can_be_boot_device": true, "model": null, "vendor": null}], "need_root": false, "need_boot": false, "install_minimum_size": 17297309696}
  ```

- POST a/storage/v2 => a/meta/confirm => success

**Comment by jbicha** [comment] 2023-07-19 17:57
Actually, I tried with 20GB which I believe was enough for Ubuntu 23.04.

**Comment by jpnurmi** [comment] 2023-07-20 09:12
Fixed by:
- https://github.com/canonical/subiquity/pull/1729

The fix won't make it on today's live because it was just pulled in a while ago but I tested with a 20GB disk and `snap refresh ubuntu-desktop-installer` and it installed fine. :+1:

```
latest/stable:    0+git.7fe84a1e 2023-07-20 (1165) 135MB classic
```

**Closed by jpnurmi** 2023-07-20 09:12 UTC
Labels: jira
