### ISSUE TITLE
No image 30th August 2022

### ISSUE THREAD

**Issue by bittin** [canonical/ubuntu-desktop-installer#1096] opened 2022-08-31 05:29 UTC
There was no image released yesterday, was it intentional?

**Comment by bittin** [comment] 2022-08-31 06:52
got an answer from @seb128 mirrors was down and had some problems yesterday

**Comment by seb128** [comment] 2022-08-31 07:07
closing since it was an infrastructure issue and not a bug in the installer

**Closed** 2022-08-31 07:07 UTC
