### ISSUE TITLE
"Detect keyboard layout" dialog doesn't work as expected

### ISSUE THREAD

**Issue by oSoMoN** [canonical/ubuntu-desktop-installer#303] opened 2021-09-13 17:45 UTC
I'm testing the installer from a local checkout, with a fr_FR.UTF-8 locale, and fr (bépo) keyboard layout (both correctly selected by default).
On the keyboard layout screen, if I click the "Detect keyboard layout" button and then press "n" (which is one of the suggested characters), the following exception is raised, and Turkish is being selected as the keyboard layout. Additionally, keyboard input in text fields doesn't work any longer in the application.

    flutter: ERROR ubuntu_desktop_installer: Unhandled exception
	    _AssertionError: 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 444 pos 16: '_pressedKeys[event.physicalKey] == event.logicalKey': A KeyUpEvent is dispatched, but the state shows that the physical key is pressed on a different logical key. If this occurs in real application, please report this bug to Flutter. If this occurs in unit tests, please ensure that simulated events follow Flutter's event model as documented in `HardwareKeyboard`. This was the event: KeyUpEvent#2592b(physicalKey: PhysicalKeyboardKey#70033(usbHidUsage: "0x00070033", debugName: "Semicolon"), logicalKey: LogicalKeyboardKey#00079(keyId: "0x00000079", keyLabel: "Y", debugName: "Key Y"), character: null, timeStamp: 13:44:58.949000) and the recorded logical key LogicalKeyboardKey#0006e(keyId: "0x0000006e", keyLabel: "N", debugName: "Key N")
    #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
    #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
    #2      HardwareKeyboard._assertEventIsRegular.<anonymous closure> (package:flutter/src/services/hardware_keyboard.dart:444:16)
    #3      HardwareKeyboard._assertEventIsRegular (package:flutter/src/services/hardware_keyboard.dart:452:6)
    #4      HardwareKeyboard.handleKeyEvent (package:flutter/src/services/hardware_keyboard.dart:543:5)
    #5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:821:35)
    #6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:73:49)
    #7      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:72:47)
    #8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:379:35)
    #9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:376:46)
    #10     _invoke2.<anonymous closure> (dart:ui/hooks.dart:205:15)
    #11     _rootRun (dart:async/zone.dart:1428:13)
    #12     _CustomZone.run (dart:async/zone.dart:1328:19)
    #13     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
    #14     _invoke2 (dart:ui/hooks.dart:204:10)
    #15     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
    #16     _Channel.push (dart:ui/channel_buffers.dart:132:31)
    #17     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
    #18     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:544:22)
    #19     _dispatchPlatformMessage (dart:ui/hooks.dart:92:31)

**Comment by jpnurmi** [comment] 2021-09-13 18:43
This bug (Alt+TAB -> hot restart -> Alt+TAB) has been there in Flutter for a good while and even landed in the latest stable 2.5.0 release:  https://github.com/flutter/flutter/issues/87391 :(

**Comment by jpnurmi** [comment] 2021-09-20 11:33
The issue has been fixed in the Flutter engine. Presumably, the fix will be cherry-picked to Flutter 2.5.2.

https://github.com/flutter/flutter/issues/87391

**Comment by jpnurmi** [comment] 2021-11-18 10:49
I'm closing this because it's being taken care of in Flutter. There was some keyboard refactoring during the summer and the aftermath is still ongoing:
- https://github.com/flutter/flutter/issues/93278
- https://github.com/flutter/flutter/issues/91064
- https://github.com/flutter/flutter/issues/87391
- https://github.com/flutter/flutter/issues/89982
- ...

**Comment by dkwingsmt** [comment] 2021-11-19 00:04
Actually if you're still encountering this bug we'd appreciate it if you leave it open. Can you check if it's still in the latest main?

**Comment by dkwingsmt** [comment] 2021-11-19 02:21
(Came with the reference from the Flutter issue.)

Hi, my apology from the disturbance. Although we're indeed trying our best to fix known bugs of the keyboard system, it's not guaranteed that this issue is recorded as an open ticket. 

Nevertheless, I think this should have been fixed by https://github.com/flutter/engine/pull/29550, which is applied to revisions after [4172c7dc005e18c7faec1ea0108cbb4de85ad4a8](https://github.com/flutter/flutter/commit/4172c7dc005e18c7faec1ea0108cbb4de85ad4a8) (Nov. 8). It's not available on any other channels than `main` at the moment. I'd appreciate it if you can test it once you test it again once the fix is in, and if it persists, open a Flutter ticket with a reproduction sample. Thank you.

**Comment by jpnurmi** [comment] 2021-11-19 08:04
Hi! Sure, we can keep this open as a reminder. I must say I already got used to restarting the app and started ignoring the errors. I tend to switch the channels back and forth for various reasons so I'm not sure if I have faced the error on the master channel recently, but I'll try to pay more attention to it. The master channel definitely works a lot better - thanks for your work on it.

**Comment by jpnurmi** [comment] 2021-11-19 13:08
@dkwingsmt It's hard to come up with reproducible steps, but somehow I managed to get this with Flutter master when running https://github.com/jpnurmi/where_are_you from VS Code.

```
Launching lib/main.dart on Linux in debug mode...
** (where_are_you:108291): WARNING **: 13:59:44.504: Unable to retrieve framework response: Message is not valid JSON
** (where_are_you:108291): WARNING **: 13:59:44.544: Unable to retrieve framework response: Message is not valid JSON
** (where_are_you:108291): WARNING **: 13:59:44.616: Unable to retrieve framework response: Message is not valid JSON
** (where_are_you:108291): WARNING **: 13:59:44.708: Unable to retrieve framework response: Message is not valid JSON
** (where_are_you:108291): WARNING **: 13:59:44.776: Unable to retrieve framework response: Message is not valid JSON
Connecting to VM Service at ws://127.0.0.1:33425/tuNOg7Et_HY=/ws
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:flutter/src/services/hardware_keyboard.dart': Failed assertion: line 787 pos 16: 'false': Should never encounter KeyData when transitMode is rawKeyData.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      KeyEventManager.handleKeyData
#3      PlatformDispatcher._dispatchKeyData.<anonymous closure> (dart:ui/platform_dispatcher.dart:375:61)
#4      _invoke2.<anonymous closure> (dart:ui/hooks.dart:189:15)
#5      _rootRun (dart:async/zone.dart:1426:13)
#6      _CustomZone.run (dart:async/zone.dart:1328:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#8      _invoke2 (dart:ui/hooks.dart:188:10)
#9      PlatformDispatcher._dispatchKeyData (dart:ui/platform_dispatcher.dart:373:5)
#10     _dispatchKeyData (dart:ui/hooks.dart:93:31)
```

Is this related to the issues at hand, or is it an unrelated platform channel communication issue between the FW and engine, where the symptoms happen to look similar?

The Flutter version is:
```
Flutter 2.6.0-12.0.pre.757 • channel master • https://github.com/flutter/flutter.git
Framework • revision 1ba81373ee (34 hours ago) • 2021-11-17 22:01:34 -0500
Engine • revision a3ef1d5351
Tools • Dart 2.16.0 (build 2.16.0-20.0.dev) • DevTools 2.8.0
```

**Closed** 2022-08-09 10:01 UTC
