### ISSUE TITLE
It seems like "English" defaults to US English when it should be British English

### ISSUE THREAD

**Issue by getsnoopy** [canonical/ubuntu-desktop-installer#2386] opened 2023-11-04 03:23 UTC
### What happened?

Upon booting into the live image, it's immediately apparent that it has been booted into using some sort of US-based locale (by the date format that's shown in the menu bar at the top being in the "Mon DD" format), but it seems like the installer just gives the option of "English" with no specification, and ends up choosing the US English locale (`en-US`) in the background.

### What was expected?

This is a poor choice for a plethora of reasons:
1. British and international English are [the most used variants of English](https://en.wikipedia.org/wiki/American_and_British_English_spelling_differences#/media/File:Defence_Defense_Labour_Labor_British_American_spelling_by_country.svg) around the world.
2. The MDY date format is [used solely by the US](https://en.wikipedia.org/wiki/Date_format_by_country#/media/File:Date_format_by_country_NEW.svg), or by 2 countries in total if being generous (since Canada sometimes writes their full-text dates in that order).
3. The 24-hour clock is [used by an overwhelming majority of the world in writing](https://en.wikipedia.org/wiki/24-hour_clock#/media/File:12_24_Hours_World_Map.svg).
4. US customary units are [used only by the US and Liberia](https://en.wikipedia.org/wiki/International_System_of_Units#/media/File:Metric_and_imperial_systems_(2019).svg), while every other country in the world (barring Myanmar) uses metric units.
5. Consequently, the ISO paper sizes are [used by an overwhelming majority of the world](https://en.wikipedia.org/wiki/Paper_size#/media/File:Prevalent_default_paper_size.svg).
6. Last but not least, Canonical is a company that originates in South Africa and is headquartered in the UK.

As such, I can't see how it makes any sense at all to be defaulting to US English in the installer and live image, especially when the user is given no indication that that's what's being chosen for them. As a result, the overwhelming majority of English speakers have to go through the installer, and then go into the System Settings and change both their locale and their "Formats" settings to an appropriate international one. This is a really bad UX, and should be fixed by changing the default to British English (`en-GB`), which will default to the international variants by default.

### Steps to reproduce

1. Insert live image into computer.
2. Boot into it.
3. Notice that the live image is booted into a US English locale.
4. Install the OS using the **English** language onto the computer.
5. Reboot and log into the installed OS.
6. Notice that the locale of English that has been installed is US English and formats by default.
7. Verify that this is the case by going into the System Settings app and into the **Region & Language** section.

**Comment by gunnarhj** [comment] 2023-11-16 17:06
There is a similar bug in Launchpad: https://launchpad.net/bugs/2043609

While I can confirm that it defaults to en_US, I don't think that only changing the default to en_GB would be desirable.

The old installer makes use of the time zone location to "guess" the desired locale. I suppose that is a reasonable approach as long as the installer does not offer a specific setting for the purpose.

**Comment by vanvugt** [comment] 2023-11-20 06:18
Duplicate of #2324

**Closed by vanvugt** 2023-11-20 06:18 UTC
Labels: bug
