### ISSUE TITLE
pager doesn't change between the first two steps

### ISSUE THREAD

**Issue by tim-hm** [canonical/ubuntu-desktop-installer#1592] opened 2023-03-10 16:14 UTC
## Issue

On the welcome screen dot one is selected in the pager, but when you move to the 2nd screen the pager stays on the first dot.

[Screencast from 2023-03-10 16-14-23.webm](https://user-images.githubusercontent.com/1335525/224366963-8e56ca99-e48e-41a6-83ca-cb85f8abf600.webm)

**Comment by d-loose** [comment] 2023-03-14 09:24
Currently, this is by design. Since some pages are optional and the path through the wizard can branch off at several points, some pages are grouped into the same "installation step", which is what the indicator shows.
The same is happening here, where it might seem more intuitive:

[Screencast from 2023-03-14 10-21-25.webm](https://user-images.githubusercontent.com/113362648/224955469-22376321-9729-443d-acbb-9f8e700adf53.webm)

Is there any way we can make this clearer?

**Comment by elioqoshi** [comment] 2023-03-15 06:18
This was the reason we had no page indicators in the beginning but re-introduced them as we thought we can deal with this compromise. 

> Currently, this is by design.

I agree that branching should be considered here. It's not sensible how some screens are grouped however (e.g I'd expect language selection and try or install to be 2 separate steps and not grouped in the same one, no?

Do we have currently a list of screens and in which steps they are grouped? cc @jpnurmi

**Comment by jpnurmi** [comment] 2023-03-15 06:37
_Try or install_ is a special screen because it's only shown on the first run. In Ubiquity, these options were on the welcome screen.

We have defined the following installation steps:

1. welcome
    - welcome
    - try or install
    - turn off rst
2. keyboard
    - keyboard layout
3. network
    - connect to internet
4. software
    - updates and other software
5. type
    - configure secure boot
    - installation type
6. storage
    - turn off bitlocker
    - install alongside
    - select guided storage
    - choose security key
    - allocate disk space
    - write changes to disk
7. location
    - where are you
8. user
    - who are you
    - configure active directory
9. look
    - choose your look

The most complicated step is the "storage" step where the shown screens depend on both, the detected hardware and your selections in the GUI. And there's even a way to jump straight from "install alongside" to manual partitioning if you change your mind and need more complicated partitioning.

**Comment by elioqoshi** [comment] 2023-03-15 06:42
> _Try or install_ is a special screen because it's only shown on the first run. In Ubiquity, these options were on the welcome screen.
> 
> We have defined the following installation steps:
> 
>     1. welcome
>        
>        * welcome
>        * try or install
>        * turn off rst

Try or install and turn off RST should be grouped separately I'd say. So:

 1. welcome 
* Select language
2. installation 
* try or install
* turn off rst

**Comment by jpnurmi** [comment] 2023-03-15 06:45
I feel like we could leave out the progress indicator on those "Turn off XXX" pages because at that point you have reached the end and there's nowhere to progress :)

![image](https://user-images.githubusercontent.com/140617/225227977-ac1bed18-e40d-4e51-89c7-a379a8db71e4.png)

**Comment by jpnurmi** [comment] 2023-03-15 07:00
Originally, we didn't want to add the dots at all because the flow is not simple and linear with all steps known upfront as it may look on the surface. :) The total amount of steps depends on your hardware and selections, and there are even some shortcuts to jump from one branch to another. We agreed to keep it simple, keep the total amount of dots constant, and use the dots to provide a simplified overview of the progress by grouping the dynamic parts as one step.

**Comment by elioqoshi** [comment] 2023-03-15 07:11
> I feel like we could leave out the progress indicator on those "Turn off XXX" pages because at that point you have reached the end and there's nowhere to progress :)

Agreed.

> We agreed to keep it simple, keep the total amount of dots constant, and use the dots to provide a simplified overview of the progress by grouping the dynamic parts together.

Yeah it's a blurry topic. I have ideas how to improve that but not appropriate for now. I think we can close this and consider improving it in the future as it's not a simple fix.

**Closed by elioqoshi** 2023-03-15 07:11 UTC
