### ISSUE TITLE
Stop hiding full disk encryption option under 'Advanced features'

### ISSUE THREAD

**Issue by dylanmtaylor** [canonical/ubuntu-desktop-installer#1678] opened 2023-03-18 15:44 UTC
Putting full disk encryption under "advanced features" is irresponsible, as it is not easily visible to users, and it's VERY hard to enable after an installation has taken place. I believe that enabling encryption is important enough to warrant a whole screen in the installation process, with an option to zero the disk and use the whole thing for additional security (FDE) being present.

**Comment by elioqoshi** [comment] 2023-03-29 08:58
@dylanmtaylor You are very right. We did not have capacities to address this in the current cycle anymore, but this is planned for 23.10

**Comment by iainlane** [comment] 2023-04-05 08:27
This this is a duplicate of #814, but obviously very correct :D

**Closed** 2023-04-26 15:41 UTC
Labels: UX/UI
